# Generated by Django 5.1.2 on 2026-08-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sentiment_analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment_label',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment_text_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
